apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  replicas: 2
  revisionHistoryLimit: 20
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      name: hello-world
      labels:
        app: hello-world
      annotations:
        kubernetes.io/change-cause: "amigoscode/kubernetes:hello-world-v4"
    spec:
      containers:
        - name: hello-world
          image: amigoscode/kubernetes:hello-world-v4
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
      restartPolicy: Always
  selector:
    matchLabels:
      app: hello-world
